export const cars = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    color: "Red",
    location: "New York",
    price: "$50/day",
    availability: true,
  },
  {
    id: 2,
    make: "Honda",
    model: "Civic",
    color: "Blue",
    location: "San Francisco",
    price: "$40/day",
    availability: true,
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    color: "Yellow",
    location: "Los Angeles",
    price: "$60/day",
    availability: true,
  },
  {
    id: 4,
    make: "Chevrolet",
    model: "Camaro",
    color: "Black",
    location: "Chicago",
    price: "$55/day",
    availability: true,
  },
  {
    id: 5,
    make: "Nissan",
    model: "Altima",
    color: "White",
    location: "Houston",
    price: "$45/day",
    availability: true,
  },
  {
    id: 6,
    make: "Tesla",
    model: "Model 3",
    color: "Red",
    location: "Miami",
    price: "$65/day",
    availability: true,
  },
  {
    id: 7,
    make: "Subaru",
    model: "Outback",
    color: "Blue",
    location: "Dallas",
    price: "$55/day",
    availability: true,
  },
  {
    id: 8,
    make: "Volkswagen",
    model: "Jetta",
    color: "Black",
    location: "San Diego",
    price: "$50/day",
    availability: true,
  },
  {
    id: 9,
    make: "Mazda",
    model: "Mazda3",
    color: "White",
    location: "Austin",
    price: "$45/day",
    availability: true,
  },
  {
    id: 10,
    make: "Kia",
    model: "Sorento",
    color: "Red",
    location: "Seattle",
    price: "$60/day",
    availability: true,
  },
];

export const bookings = [
  {
    id: 1,
    user: "John Doe",
    carId: 1,
    startDate: "2024-12-20",
    endDate: "2024-12-25",
    status: "Confirmed",
  },
];